### NumPy para mejorar el análisis de datos financieros de varias acciones a lo largo del tiempo.


1. Setup y creación del array 5x5

    Este bloque crea la matriz de datos financieros simulados, cumpliendo el punto de carga y estructuración de datos.


In [8]:
import numpy as np

# Semilla para reproducibilidad
np.random.seed(42)

# Matriz 5x5 de precios simulados (por ejemplo entre 10 y 100)
precios = np.random.uniform(10, 100, size=(5, 5))
# Filas = acciones A1..A5, columnas = días D1..D5
print("Precios:\n", precios)


Precios:
 [[43.7086107  95.56428758 75.87945476 63.87926358 24.04167764]
 [24.03950683 15.2275251  87.95585312 64.10035106 73.726532  ]
 [11.85260449 97.29188669 84.91983767 29.11051996 26.36424705]
 [26.50640589 37.38180187 57.22807885 48.87505168 36.21062262]
 [65.06676053 22.55444746 36.29301837 42.9725659  51.04629858]]


2. Estadísticos por acción

    Aquí se usan operaciones vectorizadas de NumPy para obtener métricas sin bucles explícitos

In [9]:
# Promedio, máximo y mínimo por acción (a lo largo de los días)
promedios = precios.mean(axis=1)
maximos = precios.max(axis=1)
minimos = precios.min(axis=1)

print("Promedios por acción:", promedios)
print("Máximos por acción:", maximos)
print("Mínimos por acción:", minimos)


Promedios por acción: [60.61465885 53.00995362 49.90781917 41.24039218 43.58661817]
Máximos por acción: [95.56428758 87.95585312 97.29188669 57.22807885 65.06676053]
Mínimos por acción: [24.04167764 15.2275251  11.85260449 26.50640589 22.55444746]


3. Variación porcentual diaria

    La operación se hace por filas y columnas de forma vectorizada, cumpliendo el requisito de variación porcentual.


In [10]:
# Variación porcentual diaria: (precio_t - precio_(t-1)) / precio_(t-1)
# Resultado: matriz 5x4 (porque se pierden los primeros días en el cálculo)
variacion_pct = (precios[:, 1:] - precios[:, :-1]) / precios[:, :-1]

print("Variación porcentual diaria:\n", variacion_pct)


Variación porcentual diaria:
 [[ 1.18639499 -0.20598524 -0.15814809 -0.62363878]
 [-0.3665625   4.77610955 -0.27122131  0.15017361]
 [ 7.20848167 -0.12716424 -0.6572     -0.09433953]
 [ 0.41029312  0.53090745 -0.14596029 -0.25911848]
 [-0.65336452  0.60912913  0.18404497  0.18788109]]


4. Funciones matemáticas sobre los datos

    Se aplica logaritmo, normalización y exponencial usando broadcasting para adaptar las dimensiones automáticamente.


In [11]:
# Logaritmo natural de los precios
log_precios = np.log(precios)

# Exponencial de los precios normalizados
# Normalización min-max por acción:
min_accion = precios.min(axis=1).reshape(-1, 1)
max_accion = precios.max(axis=1).reshape(-1, 1)
precios_norm = (precios - min_accion) / (max_accion - min_accion)

exp_precios_norm = np.exp(precios_norm)

print("Log de precios:\n", log_precios)
print("Precios normalizados:\n", precios_norm)
print("Exponencial de precios normalizados:\n", exp_precios_norm)


Log de precios:
 [[3.77754512 4.55979919 4.32914596 4.1569948  3.17978889]
 [3.17969859 2.72310465 4.47683502 4.16044984 4.30036273]
 [2.47254763 4.5777156  4.44170773 3.37109962 3.27200881]
 [3.27738644 3.621184   4.04704467 3.88926708 3.58935252]
 [4.17541383 3.11593227 3.59162539 3.76056191 3.93273304]]
Precios normalizados:
 [[0.27497505 1.         0.72477469 0.5569929  0.        ]
 [0.12116299 0.         1.         0.67199161 0.80434967]
 [0.         1.         0.85519484 0.20199041 0.16984743]
 [0.         0.35399752 1.         0.72810637 0.31587527]
 [1.         0.         0.32316686 0.48028717 0.67020233]]
Exponencial de precios normalizados:
 [[1.31649782 2.71828183 2.06426594 1.74541596 1.        ]
 [1.12880888 1.         2.71828183 1.95813327 2.23524239]
 [1.         2.71828183 2.35183256 1.22383627 1.18512402]
 [1.         1.42475165 2.71828183 2.07115489 1.37145918]
 [2.71828183 1.         1.38149585 1.61653855 1.95463275]]


5. Indexación avanzada y selección

    Estas operaciones demuestran indexación avanzada para obtener datos específicos del array.

In [12]:
# Ejemplo: rendimiento (precio) de la acción 2 en el día 4
# (recuerda que Python indexa desde 0)
accion_idx = 1  # segunda fila
dia_idx = 3     # cuarto día
precio_especifico = precios[accion_idx, dia_idx]
print("Precio acción 2 día 4:", precio_especifico)

# Extraer todas las acciones en el día 3
precios_dia3 = precios[:, 2]
print("Precios en el día 3:", precios_dia3)

# Extraer un subconjunto: acciones 1, 3 y 5 en días 2 y 5
acciones_idx = [0, 2, 4]
dias_idx = [1, 4]
subconjunto = precios[np.ix_(acciones_idx, dias_idx)]
print("Subconjunto acciones [1,3,5] días [2,5]:\n", subconjunto)


Precio acción 2 día 4: 64.1003510568888
Precios en el día 3: [75.87945476 87.95585312 84.91983767 57.22807885 36.29301837]
Subconjunto acciones [1,3,5] días [2,5]:
 [[95.56428758 24.04167764]
 [97.29188669 26.36424705]
 [22.55444746 51.04629858]]


6. Ejemplo de comparación sin NumPy (listas puras)

    Este fragmento te sirve para el informe comparativo mostrando cómo sería con listas y bucles anidados.

In [13]:
# Supongamos que convertimos la matriz NumPy a lista de listas
precios_list = precios.tolist()

# Cálculo del promedio por acción sin NumPy
promedios_sin_numpy = []
for fila in precios_list:
    suma = 0
    for valor in fila:
        suma += valor
    promedio = suma / len(fila)
    promedios_sin_numpy.append(promedio)

print("Promedios sin NumPy:", promedios_sin_numpy)


Promedios sin NumPy: [60.61465885074682, 53.009953620734656, 49.90781917258471, 41.240392179136606, 43.58661816556661]


### Introducción

    En este caso se aborda la aplicación de la librería NumPy para optimizar el análisis de datos financieros simulados, específicamente precios de acciones en distintos días de cotización. El objetivo es mejorar la eficiencia del procesamiento numérico mediante arrays multidimensionales, operaciones vectorizadas y técnicas de broadcasting, en contraste con métodos tradicionales basados en listas y bucles.


#### Desarrollo técnico de la solución

    Para la carga y estructuración de datos se generó un array NumPy de dimensión 5x5 con valores aleatorios continuos, donde cada fila representa una acción y cada columna un día de cotización, lo que permite trabajar con una estructura matricial homogénea de tipo numérico. Esta representación facilita la aplicación de operaciones agregadas sobre filas y columnas sin necesidad de transformar los datos en cada paso.
​

    En la fase de análisis y transformación se calcularon, por cada acción, el promedio, valor máximo y mínimo empleando métodos como mean, max y min con axis=1, lo que resume el comportamiento temporal de cada activo. Además, se obtuvo la variación porcentual diaria mediante una operación vectorizada que compara columnas consecutivas, y se aplicaron funciones matemáticas como el logaritmo natural, la normalización min–max por acción y la exponencial sobre los datos normalizados, utilizando broadcasting para ajustar automáticamente las dimensiones de los arrays de mínimos y máximos.
​

    Para la optimización y selección de datos se hizo uso de indexación avanzada, permitiendo extraer valores específicos como el precio de una acción en un día concreto, así como subconjuntos de acciones y días mediante combinaciones de índices e np.ix_. Estas técnicas permiten seleccionar y combinar porciones del dataset sin copiar datos innecesariamente, manteniendo un acceso eficiente a la información relevante.


#### Comparación con métodos sin NumPy

    Las mismas tareas se implementaron también con listas de listas y bucles explícitos, por ejemplo, para calcular promedios por acción iterando sobre cada fila y acumulando manualmente las sumas. Este enfoque requiere más líneas de código, es menos declarativo y aumenta la probabilidad de errores lógicos o de índice, además de ser menos eficiente en términos de rendimiento al no aprovechar operaciones vectorizadas a nivel de bajo nivel.
​

    En cambio, el uso de NumPy concentra la lógica en llamadas a funciones optimizadas en C y Fortran, lo que reduce el tiempo de ejecución especialmente cuando crece el tamaño de los datos. Además, la legibilidad mejora al expresar las operaciones de forma más cercana a la notación matemática, facilitando el mantenimiento y la extensión de la solución a nuevos cálculos o dimensiones.
​

#### Conclusiones

    NumPy demuestra ser una herramienta clave para la manipulación y análisis de datos numéricos en contextos financieros, al permitir trabajar con arrays multidimensionales, funciones estadísticas y matemáticas, e indexación avanzada de forma eficiente. Frente a los métodos tradicionales sin NumPy, ofrece una reducción significativa en complejidad de código y una mejora notable en rendimiento computacional, lo que resulta especialmente valioso cuando se procesan grandes volúmenes de datos y se requieren métricas en tiempo casi real.
​

    Si quieres, en el siguiente mensaje se puede pulir el texto para que encaje exactamente con el formato o extensión que te pida tu plataforma (por ejemplo, separar en secciones numeradas o agregar comentarios dentro del código).